/**
 * Lockstep Platform SDK for TypeScript
 *
 * (c) 2021-2023 Lockstep, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author     Lockstep Network <support@lockstep.io>
 * @copyright  2021-2023 Lockstep, Inc.
 * @link       https://github.com/Lockstep-Network/lockstep-sdk-typescript
 */


/**
 * Represents the email reply suggestion from the SAGE GMS API
 */
export type EmailReplyGeneratorSuggestions = {

  /**
   * The kind of reply generated by the GMS Api
   */
  kind: string | null;

  /**
   * The body of the reply generated by the GMS Api
   */
  body: string | null;
};
