/**
 * Lockstep Platform SDK for TypeScript
 *
 * (c) 2021-2023 Lockstep, Inc.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author     Lockstep Network <support@lockstep.io>
 * @copyright  2021-2023 Lockstep, Inc.
 * @link       https://github.com/Lockstep-Network/lockstep-sdk-typescript
 */


/**
 * Represents transaction detail information associated to a transaction. This can either be Invoices which are paid with a
 * Credit Memo or Payment transaction, or Credit Memos or Payments used as payment for an Invoice transaction.
 */
export type TransactionDetailModel = {

  /**
   * Group account transaction detail is associated with.
   */
  groupKey: string;

  /**
   * The base currency code of the group.
   */
  baseCurrencyCode: string | null;

  /**
   * An additional reference number that is sometimes used to identify a transaction detail.
   * The meaning of this field is specific to the ERP or accounting system used by the user.
   */
  referenceNumber: string | null;

  /**
   * The unique ID of the transaction detail record.
   */
  transactionDetailId: string;

  /**
   * The unique ID of the entity applying the transaction to the transaction detail record.
   */
  transactionDetailAppliedId: string;

  /**
   * The unique ID of the transaction record.
   */
  transactionId: string;

  /**
   * The type of the transaction detail record.
   *
   * Recognized Invoice types are:
   * * `AR Invoice` - Represents an invoice sent by Company to the Customer
   * * `AP Invoice` - Represents an invoice sent by Vendor to the Company
   * * `AR Credit Memo` - Represents a credit memo generated by Company given to Customer
   * * `AP Credit Memo` - Represents a credit memo generated by Vendor given to Company
   *
   * Recognized PaymentType values are:
   * * `AR Payment` - A payment made by a Customer to the Company
   * * `AP Payment` - A payment made by the Company to a Vendor
   */
  transactionType: string | null;

  /**
   * Additional type categorization of the transaction.
   */
  transactionSubType: string | null;

  /**
   * The date when a transaction detail record was reported.
   */
  transactionDate: string | null;

  /**
   * The date of the invoice associated to the transaction detail record.
   */
  transactionInvoiceDate: string;

  /**
   * The currency code of the transaction.
   */
  currencyCode: string | null;

  /**
   * The total value of this transaction detail, inclusive or all taxes and line items.
   */
  transactionAmount: number;

  /**
   * The remaining balance of this transaction detail.
   */
  outstandingAmount: number | null;

  /**
   * The total value of this transaction detail, inclusive or all taxes and line items in the group's base currency.
   */
  baseCurrencyTransactionAmount: number;

  /**
   * The remaining balance of this transaction detail in the group's base currency.
   */
  baseCurrencyOutstandingAmount: number | null;

  /**
   * Specific transactions have support for pdf retrieval from their respective erp. When this flag is true, an additional
   * call to Invoices/{id}/pdf or Payments/{id}/pdf can be made to retrieve a pdf directly from the erp.
   */
  supportsErpPdfRetrieval: boolean;
};
